### ISSUE TITLE
probably just a file was wrong

### ISSUE THREAD

**Issue by ak491** [jmathai/elodie#377] opened 2020-05-29 04:53 UTC
./201012/201012A0/06122010210.jpg -> /media/HDD/FOTOS_elodie_test/2010-12-Dec/Unknown Location/2010-12-06_12-05-06-06122010210.jpg
Traceback (most recent call last):
  File "/home/osmc/elodie/elodie.py", line 378, in <module>
    main()
  File "/home/osmc/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/osmc/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/osmc/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/osmc/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/osmc/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/osmc/elodie/elodie.py", line 141, in _import
    trash, allow_duplicates)
  File "/home/osmc/elodie/elodie.py", line 41, in import_file
    _file = _decode(_file)
  File "/home/osmc/elodie/elodie/compatability.py", line 23, in _decode
    return string.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 12: ordinal not in range(128)

**Comment by jmathai** [comment] 2021-01-11 07:25
Duplicate of #267 and #253.

Per [this comment](https://github.com/jmathai/elodie/issues/267#issuecomment-552595467), you might not see the problem if you're using python 3.

**Closed by jmathai** 2021-01-11 07:25 UTC
