### ISSUE TITLE
Fix/review custom folder structure fallbacks #Help #Question

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#306] opened 2019-03-31 02:39 UTC
https://github.com/jmathai/elodie/pull/283

Hey @jmathai,

Hope you're well

Thanks for software, as always

As title

I won't go into detail with my desired syntax (yet), instead I'll simply use the README example[e] syntax:

```
[Directory]
month=%m
year=%Y
location=%city
full_path=%month/%year/%album|%location|%"Beats me"
```

... which yields unexpected results, where I see ``Unknown Location`` instead of ``Beats me``:

```
Last login: Sun Mar 31 04:00:31 on ttys000
Lewiss-MacBook-Pro:~ ldexterldesign$ tree /Users/ldexterldesign/Desktop/elodie/-source
/Users/ldexterldesign/Desktop/elodie/-source
└── 2009-03-20_21-29-43-dsc_0248.jpg

0 directories, 1 file
Lewiss-MacBook-Pro:~ ldexterldesign$ tree /Users/ldexterldesign/Desktop/elodie/-destination
/Users/ldexterldesign/Desktop/elodie/-destination
└── 03
    └── 2009
        └── Unknown\ Location
            └── 2009-03-20_21-29-43-dsc_0248.jpg

3 directories, 1 file
Lewiss-MacBook-Pro:~ ldexterldesign$
```

![2009-03-20_21-29-43-dsc_0248](https://user-images.githubusercontent.com/1715809/55283972-d618c900-536d-11e9-8ee8-66ec7570d98b.jpg)

If you have any issues (e.g. questions/queries) then happy to help

Hope this is helpful and to hear back

Cheers

e: https://github.com/jmathai/elodie#using-fallback-folders

hardware: Apple, MacBook Pro (Retina, 15-inch, Mid 2014)
software - operating system: Apple, macOS, 10.14.4 (18E226)

**Comment by ldexterldesign** [comment] 2019-03-31 02:46
```
Last login: Sun Mar 31 04:29:54 on ttys001
Lewiss-MacBook-Pro:~ ldexterldesign$ which python
/usr/local/bin/python
Lewiss-MacBook-Pro:~ ldexterldesign$ python --version
Python 2.7.16
```

OK?

**Comment by jmathai** [comment] 2019-04-01 15:50
This is specific to `location`, right? If so, it's known behavior because `geolocation.py` returns `Unknown Location` if it can't find a location and the path generation logic doesn't distinguish between `Unknown Location` and an actual location name. Fallbacks are only supported for return values which are `falsey`.

The 2 options are to handle parsing `Unknown Location` in the path generation logic or add an option not to default to `Unknown Location`.

I probably prefer the former since the default is in place since a sizable number of photos don't have geolocation in EXIF as opposed to something like date/time.

**Comment by ldexterldesign** [comment] 2019-04-03 22:38
Thanks for reply

> This is specific to location, right?

Yea, sorry I should have been more specific

> If so, it's known behavior because geolocation.py returns Unknown Location if it can't find a location and the path generation logic doesn't distinguish between Unknown Location and an actual location name. Fallbacks are only supported for return values which are falsey.

I see, things are clearer now

My understanding is it's impossible to use fallbacks with %location because it can never yield a falsey value (i.e. if no GPS tags or map API can't match then *always* "Unknown Location" which is truthy). If this is correct then the following is misleading:

> If there's no GPS in the EXIf then I should name the last folder `Beats me`. - https://github.com/jmathai/elodie/blame/master/Readme.md#L219

The "Beats me" example config' was the first thing I tried when testing the custom file naming feature and I could never generate "Beats me" so a) I felt stupid then b) I suspected a bug then c) you had to explain

If correct then I think the README could be enhance, but given the non-technical tone I'm not sure what to suggest

Hope to hear back

Cheers

**Comment by ldexterldesign** [comment] 2019-04-03 23:09
```
[Directory]
date=%Y-%m
location=%country - %state - %city
custom=%camera_make - %camera_model
full_path=%date/%camera_make/%location
```

```shell
/Users/ldexterldesign/Applications/elodie/-destination
└── 2018-02
    ├── LGE
    │   ├── Malta\ -
    │   │   └── 2018-02-13_08-58-09-2018-02-13-09.58.09.jpg
    │   └── Unknown\ Location
    │       └── 2018-02-05_13-17-55-2018-02-05-14.17.55.jpg
    └── Unknown\ Location
        └── 2018-02-11_06-29-10-2018-02-11-08.29.10.mp4

5 directories, 3 files
```

**Comment by ldexterldesign** [comment] 2019-04-03 23:47
For the moment I'm content with this:

```
[Directory]
custom=%camera_make - %camera_model
date=%Y-%m
location=%country - %state - %city
full_path=%date/%custom/%location
```

```
/Users/ldexterldesign/Applications/elodie/-destination
├── 2018-01
│   └── LGE\ -\ Nexus\ 5X
│       └── Malta\ -
│           ├── 2018-01-14_17-11-37-2018-01-14-18.11.37.jpg
│           ├── 2018-01-28_12-20-10-2018-01-28-13.20.10.jpg
│           └── 2018-01-28_12-20-29-2018-01-28-13.20.29.jpg
├── 2018-02
│   ├── -
│   │   └── Unknown\ Location
│   │       ├── 2018-02-02_11-22-35-2018-02-02-13.22.35.mp4
│   │       └── 2018-02-11_06-29-10-2018-02-11-08.29.10.mp4
│   └── LGE\ -\ Nexus\ 5X
│       ├── Malta\ -
│       │   ├── 2018-02-13_08-58-07-2018-02-13-09.58.07-1.jpg
│       │   ├── 2018-02-13_08-58-09-2018-02-13-09.58.09.jpg
│       │   └── 2018-02-13_08-58-16-2018-02-13-09.58.16.jpg
│       └── Unknown\ Location
│           ├── 2018-02-01_11-19-33-2018-02-01-12.19.33.jpg
│           ├── 2018-02-05_13-17-55-2018-02-05-14.17.55.jpg
│           └── 2018-02-21_07-28-53-2018-02-21-08.28.53.jpg
└── 2018-03
    └── LGE\ -\ Nexus\ 5X
        ├── Malta\ -
        │   └── 2018-03-07_16-10-03-2018-03-07-17.10.03.jpg
        └── Unknown\ Location
            ├── 2018-03-04_08-16-13-2018-03-04-09.16.13-2.jpg
            └── 2018-03-06_18-16-19-2018-03-06-19.16.19.jpg

13 directories, 14 files
```

When there's a missing placeholder at least the path structure is maintained because ``-`` generates a folder

**Comment by jmathai** [comment] 2019-04-04 03:38
Thanks for the detailed response. That's a clever workaround for what I'd consider to be a bug :)

**Comment by ldexterldesign** [comment] 2019-04-04 14:20
Phew, anal paranoia averted

Cheers

**Comment by jmathai** [comment] 2019-08-23 04:32
Closing as a duplicate of #245.

**Closed by jmathai** 2019-08-23 04:32 UTC
Labels: bug
