### ISSUE TITLE
omit renaming if photo name is already in yyyy-mm-dd mm-ss format

### ISSUE THREAD

**Issue by danito** [jmathai/elodie#110] opened 2016-04-18 15:01 UTC
I've set my camera to provide yyyy-mm-dd mm-ss.jpg/raw file names (which probably wasn't the best idea), if I proceed them with Elodie I end up with yyyy-mm-dd_mm-ss-yyyy-mm-dd mm-ss.jpg which is a bit confusing.

**Comment by jmathai** [comment] 2016-04-18 16:44
Thanks @danito. I created #111 to track a solution for general customizations for a few issues related to customizing the file name and folder structure.

**Comment by jmathai** [comment] 2016-04-18 18:22
@danito if you're looking to omit the date prefix you can do it manually by changing similar lines of code as in [this comment about removing the file name](https://github.com/jmathai/elodie/issues/107#issuecomment-210255588) in [filesystem.py](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L122)....

From this.
```
        file_name = '%s-%s.%s' % (
            time.strftime(
                '%Y-%m-%d_%H-%M-%S',
                metadata['date_taken']
            ),
            base_name,
            metadata['extension'])
```

To this.

```
        file_name = '%s.%s' % (
            base_name,
            metadata['extension'])
```

**Comment by jmathai** [comment] 2016-12-31 06:35
Marking this as a duplicate of #107. We should have this option included in a couple weeks.

**Closed by jmathai** 2016-12-31 06:35 UTC
Labels: bug
