### ISSUE TITLE
Import from "Dropbox/Camera Uploads" causes program crash

### ISSUE THREAD

**Issue by misterpipine** [jmathai/elodie#162] opened 2016-12-19 21:50 UTC
when Elodie is launched to import photos from ~/Dropbox/Camera Uploads folder, an exception is raised.

The command used is :
`./elodie.py import "~/Dropbox/Camera Uploads" --destination ~/OrganizedLibrary
`

The output log is :
```
Traceback (most recent call last):
  File "./elodie.py", line 302, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 103, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 59, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/Users/pascalfosse/elodie/elodie/filesystem.py", line 208, in process_file
    checksum_file
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 33: ordinal not in range(128)
```

**Comment by jmathai** [comment] 2016-12-19 21:52
Can you try it like this?

```
./elodie.py import --source="~/Dropbox/Camera Uploads" --destination=~/OrganizedLibrary
```

**Comment by misterpipine** [comment] 2016-12-19 21:55
same result

Le lun. 19 déc. 2016 à 22:52, Jaisen Mathai <notifications@github.com> a
écrit :

**Comment by jmathai** [comment] 2016-12-19 21:58
Can you set `debug = True` in `elodie/constants.py` and paste any additional output?

**Comment by misterpipine** [comment] 2016-12-19 22:02
I'm going to try with debug mode but in fact, not exactly the same result
with "--source". Now I have this :

{"source":"/Users/pascalfosse/Dropbox/Camera Uploads", "error_msg":"Could
not find /Users/pascalfosse/Dropbox/Camera Uploads"}

****** ERROR DETAILS ******

File

-----------------------------------------

/Users/pascalfosse/Dropbox/Camera Uploads



****** SUMMARY ******

Metric      Count

--------  -------

Success         0

Error           1

2016-12-19 22:58 GMT+01:00 Jaisen Mathai <notifications@github.com>:

**Comment by jmathai** [comment] 2016-12-19 22:03
Try this.

```
./elodie.py import --source=~/Dropbox/Camera\ Uploads --destination=~/OrganizedLibrary
```

**Comment by misterpipine** [comment] 2016-12-19 22:09
same result. It's like if the space was not a space... I've tried
copy/paste of the full path from Terminal but it's the same

2016-12-19 23:03 GMT+01:00 Jaisen Mathai <notifications@github.com>:

**Comment by misterpipine** [comment] 2016-12-19 23:09
Maybe an encoding issue. For information, the following Python program : 

```
#!/usr/bin/env python
import sys
print sys.getdefaultencoding() #python
print sys.getfilesystemencoding() #OS
```
returns : 
```
ascii
utf-8
```

**Comment by jmathai** [comment] 2016-12-20 04:27
Can you update this line to be the following by adding `str()` around `path`?
https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L66

```
        for dirname, dirnames, filenames in os.walk(str(path)):
```

**Comment by misterpipine** [comment] 2016-12-20 06:08
The output message is : 
```
Could not find /Users/xxxxxxxx/Dropbox/Camera Uploads
{"source":"/Users/xxxxxxxx/Dropbox/Camera Uploads", "error_msg":"Could not find /Users/xxxxxxxxx/Dropbox/Camera Uploads"}
```

I've also created a folder "Photo Import" from the Finder (MacOS) with the command : 

`./elodie.py import --source "/Users/xxxxx/Import Photos" --destination "/Users/xxxxxx/Google Drive/Google Photos"`

and the result is : 

```
Traceback (most recent call last):
  File "./elodie.py", line 302, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 103, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 59, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/Users/pascalfosse/elodie/elodie/filesystem.py", line 188, in process_file
    dest_directory = os.path.join(destination, directory_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 38: ordinal not in range(128)
```

The output is different, but the result is unfortunately the same : Elodie has trouble with spaces in path. I cannot explain why the output of the command but I noticed such variability of the output over the time when using exactly the same command.

However, if I try the command : 
`./elodie.py import --source "/Users/xxxxx/Import" --destination "/Users/xxxxxx/Google Drive/Google Photos"`

I do not have error and the files are processed correctly. The spaces in "Google Drive" and "Google Photos" doesn't seem to be a problem.

**Comment by misterpipine** [comment] 2016-12-21 05:18
here is my suggestion for fix, in _import function in elodie.py : 
```
...
destination = os.path.abspath(os.path.expanduser(destination)).decode(sys.getfilesystemencoding())
...
paths.add(source.decode(sys.getfilesystemencoding()))
...
```
Because my filesystem is UTF-8, I have to use autocompletion in the terminal intead of typing "blablabla/Camera Uploads" due to the encoding of the non-breaking space.

With the code above, I have no more UnicodeDecodeError.

**Comment by jmathai** [comment] 2016-12-21 06:45
Did you want to submit a pull request with that change?

**Comment by jmathai** [comment] 2016-12-22 06:17
@misterpipine what version of python are you using?

**Comment by misterpipine** [comment] 2016-12-22 11:13
my Python version : 2.7.13

**Comment by ldexterldesign** [comment] 2016-12-23 03:50
+1

**Comment by jmathai** [comment] 2016-12-23 06:09
@ldexterldesign the encoding issue should be fixed in master but we'd still like to add a test case which fails without the patch and passes with. Let us know if you're able to reproduce and/or help us write that test case.

Otherwise you can see if the problem is resolved for you by pulling the latest from master.

**Comment by misterpipine** [comment] 2016-12-23 07:57
Hi @ldexterldesign

I'm using a UTF-8 filesystem and I discovered that the space character in the names of the folders or the files can be encoded differently (different space characters). In fact, if try to use quotation or backslash, I often get a "file does not exist" error, depending on the kind of space character.
To avoid such issue, I use now the autocompletion functionnality and I get this command: 

`./elodie.py import --source=~/Dropbox/Camera Uploads --destination=~/Google\ Drive/Google Photos` 

As you can see, two of these spaces looks like ascii spaces but they are not because if I type myself these spaces on the keyboard, I get a "file not found" exception (even with backslash or quotation). The command line above contains UTF-8 characters and causes an error in execution of Elodie: 
 
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 38: ordinal not in range(128)`

That's why I suggested to use `.decode(sys.getfilesystemencoding())` on the strings "source" and "destination" to avoid such error. However, we cannot reproduce the error with a TestCase and we need some help for that.

@jmathai I've pulled the latest from the master, and the problem is solved for me. Thanks.

**Comment by ldexterldesign** [comment] 2016-12-23 19:18
@misterpipine thanks for reply

Yea, I gathered you were/are way ahead of my knowledge on this; based on your PR

I was actually describing my autocomplete syntax, ha

I'll get my coat 🤗

Glad your build is working

Regards

**Comment by jmathai** [comment] 2016-12-26 22:24
Fixed +1

Thanks @misterpipine

**Closed by jmathai** 2016-12-26 22:24 UTC
Labels: bug, help wanted

**Comment by jmathai** [comment] 2016-12-26 22:28
Fixed +1

Thanks @misterpipine

**Comment by misterpipine** [comment] 2016-12-28 08:07
You're welcome @jmathai, thank you for the addition of the compatibility module. Now I have to seriously work on the strategy for my shared photo library based on Elodie and my Synology...

**Comment by floxx** [comment] 2017-08-03 18:18
My import fails with the same result. It's an export (aka takeout) of my Google Photos library.
<pre>
<code>
****** ERROR DETAILS ******
Traceback (most recent call last):
  File "./elodie.py", line 345, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 119, in _import
    result.write()
  File "/Users/florianbusch/elodie/elodie/result.py", line 29, in write
    print(tabulate(error_result, headers=error_headers))
  File "/usr/local/lib/python2.7/site-packages/tabulate.py", line 1119, in tabulate
    ['\t'.join(map(_text_type, row)) for row in list_of_lists])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 39: ordinal not in range(128)
</code>
</pre>
Shouldn't the issue be fixed, or is it another bug? And how can I identify the responsible file/path?

**Comment by jmathai** [comment] 2017-08-03 23:38
This looks like a separate issue when the results are being printed out. Do you know which photo causes this? If you can attach it here or send the original to me via email (jaisen at github username dot com) I can reproduce it.

**Comment by jmathai** [comment] 2017-08-03 23:39
> And how can I identify the responsible file/path?

Just saw that. The error should be in the file name. Do you know which files might have non ascii characters in them?
