### ISSUE TITLE
Want to put %month and %location into same level folder, but not working

### ISSUE THREAD

**Issue by ericfong** [jmathai/elodie#284] opened 2018-10-06 09:48 UTC
```
[Directory]
location=%state_%city
month=%m-%b
year=%Y

# want but not working
full_path=%year/%mont-%album|%location

# only can
full_path=%year/%month/%album|%location
```

**Comment by jmathai** [comment] 2018-10-06 18:30
Hi @ericfong - Thanks for opening the issue. This is a duplicate of #279. Please follow that issue and PR #283 which adds initial support for this.

**Closed by jmathai** 2018-10-06 18:30 UTC

**Comment by ericfong** [comment] 2018-10-07 14:27
Thx a lot
