### ISSUE TITLE
Geo Location always unknown location

### ISSUE THREAD

**Issue by NEprod** [jmathai/elodie#380] opened 2020-07-16 23:48 UTC
I have setup up elodie adding my mapquest key to config.ini and its location is in the main elodie folder.

After scanning a folder of photos taken on iphone with each photo having location data within my photos are stored in folders with unknow location

Im hoping its something simple as in the config.ini file is located in wrong place

kind Regards

**Comment by jmathai** [comment] 2020-07-16 23:57
Try adding `--debug` to the command and pasting the output here. It should show the mapquest URL which you can call to verify the location data.

**Comment by NEprod** [comment] 2020-07-17 00:02
```
C:\Users\datho\elodie> python .\elodie.py import --debug --destination="\\homepvr\storage\Photos\PiWiGo" \\homepvr\storage\Photos\02
\\homepvr\storage\Photos\02\IMG_0536.JPG -> \\homepvr\storage\Photos\PiWiGo\2020-02-Feb\Unknown Location\2020-02-23_14-53-38-img_0536.jpg
```

thats all i get when i run the command with debug it will run through the whole folder and all get an Unknown Location

**Comment by NEprod** [comment] 2020-07-17 00:13
okay im not sure whats just happened tried again and now its telling me my my AppKey is invalid its copied direct from mapquests website dose it need parenthesis or anything round.

```
[MapQuest]
key=owW6s8YYraCHxZy*******1wtW6SQS5
prefer_english_names=True
```

this is how i have my config file without *

```
\\homepvr\storage\Photos\12\IMG_0191.HEIC -> \\homepvr\storage\Photos\PiWiGo\2019-12-Dec\Unknown Location\2019-12-25_08-29-24-img_0191.heic
The AppKey submitted with this request is invalid.
No JSON object could be decoded
```

error coming up now from different folder

**Comment by jmathai** [comment] 2020-07-17 00:19
It should not - you could try enclosing it in double quotes and post back if the problem persists.

You can also try the API key used in tests - https://github.com/jmathai/elodie/blob/master/.travis.yml#L17

**Comment by NEprod** [comment] 2020-07-17 00:27
im not sure what im doing wrong now tried the API key from the link and still getting same error as above, ive also placed my API within " and still get the same error not sure whats happening. Ive also noticed im placed a directory style within the config as well and its not following this.

I have the config in a folder with the main folder as follows `C:\Users\datho\elodie\.elodie\config.ini` is this the correct place?

**Comment by jmathai** [comment] 2020-07-17 00:31
Move the `.elodie` folder to `C:\Users\datho` and try again.

**Comment by NEprod** [comment] 2020-07-17 00:37
yea thats what happens at 1.30 in the morning ha had the folder in the correct place as followed the mkdir but still created my own inside directory. calls are now been made just need to sort out the location myself now as only england is being added and not the city.

**Comment by NEprod** [comment] 2020-07-17 00:43
Unless its mapquest that doesnt recognise city names in the UK, Country gives United Kingdom State gives England but city doesnt return a value.

**Comment by NEprod** [comment] 2020-07-17 08:13
I’ve seen an issue before asking for use of Google’s api for geolocation is this possible as mapquest isn’t the greatest for the area I live in it seems to place all locations as England unless I’m at a major city then I get the City name.

Kind Regards

**Comment by jmathai** [comment] 2021-01-11 07:18
Closing as duplicate of #258.

**Closed by jmathai** 2021-01-11 07:18 UTC
